// ASP.NET + Javascript project/Javascript/vue-apartment-app/src/views/owner/OwnerEdit.vue
<template>
  <h1>Edit</h1>

  <h4>Owner</h4>
  <hr />
  <div>
    <ul>
      <li class="text-danger" v-for="error in errorMessages" :key="error">
        {{ error }}
      </li>
    </ul>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div>
        <div class="form-group">
          <label class="control-label">Name</label>
          <input v-model="name" class="form-control" type="text" />
        </div>
        <div class="form-group">
          <label class="control-label">Email</label>
          <input v-model="email" class="form-control" type="text" />
        </div>
        <div class="form-group">
          <label class="control-label">Phone</label>
          <input v-model="phone" class="form-control valid" type="number" />
        </div>
        <div class="form-group">
          <label class="control-label">Advanced Pay</label>
          <input v-model="advancedPay" class="form-control" type="number" />
        </div>

        <div class="form-group btn-group pt-3">
          <input @click="submitClicked()" type="submit" value="Edit" class="btn btn-primary" />
          <RouterLink to="/owner" class="nav-link" active-class="active"> Back to List</RouterLink>
        </div>
        <div>
    
  </div>
      </div>
    </div>
  </div>

  
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import { useIdentityStore } from "@/stores/Identity";
import { useOwnerStore } from "@/stores/owner";
import { OwnerService } from "@/service/OwnerService";

@Options({
  components: {},
  props: { id: String },
  emist: {},
})
export default class OwnerEdit extends Vue {
  id!: string;
  identityStore = useIdentityStore();
  ownerStore = useOwnerStore();
  ownerService = new OwnerService();
  errorMessages: string[] = [];

  name: string = "";
  email: string = "";
  phone: number | null = null;
  advancedPay: number | null = null;;

  async submitClicked(): Promise<void> {
    console.log("submitclicked");

    this.errorMessages = [];

    if (this.name === "") {
      this.errorMessages.push("Name cannot be empty");
    }

    if (this.phone === null) {
      this.errorMessages.push("Phone number cannot be empty");
    }

    if (this.email.length < 6) {
      this.errorMessages.push("Email must be longer than 5");
    }

    if (this.errorMessages.length === 0) {
      let appUserId = this.identityStore.$state.jwt!.appUserId;

      if (appUserId === null) {
        await this.$router.push("/");
        return;
      }

      var res = await this.ownerService.update(this.id, {
        id: this.id,
        name: {"en": this.name},
        email: this.email,
        phone: this.phone!,
        advancedPay: this.advancedPay!,
        
        appUserId: appUserId,
      });

      if (res.status >= 300 && res.errorMessage) {
        this.errorMessages.push(res.status + " " + res.errorMessage);
      } else {
        this.ownerStore.$state.owners = await this.ownerService.getAll();

        await this.$router.push("/owner");
      }
    }
  }

  async mounted() {
    console.log("mounted");
    let owner = await this.ownerService.get(this.id);
    console.log(this.ownerStore.$state.owners);
    if (owner != null) {
      this.name = owner["name"]["en"];
      this.email = owner["email"];
      this.phone = owner["phone"];
      this.advancedPay = owner["advancedPay"];
    }
  }
}
</script>

// ASP.NET + Javascript project/Javascript/react-apartment-app/src/views/owner/OwnerEdit.tsx
import { useEffect, useState } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import { Link, useNavigate, useParams } from "react-router-dom";
import { IOwner } from "../../domain/IOwner";

import { OwnerService } from "../../services/OwnerService";
import { useAppSelector } from "../../store/hooks";

const initialState: IOwner = {
    id: "",
    name: { en: "" },
    email: "",
    phone: 0,
    advancedPay: 0,
    appUserId: "",
};

interface IFormInput {
    name: string;
    email: string;
    phone: number;
    advancedPay: number;
}

function OwnerEdit() {
    let { id } = useParams();
    const ownerService = new OwnerService();
    const jwt = useAppSelector((state) => state.identity);
    const navigate = useNavigate();

    const [owner, setOwner] = useState(initialState);

    useEffect(() => {
        if (id !== undefined) {
            ownerService.get(id).then((data) => setOwner(data));
        }
    }, []);


    useEffect(() => {
        setValue("name", owner.name.en);
        setValue("email", owner.email);
        setValue("phone", owner.phone);
        setValue("advancedPay", owner.advancedPay);
    }, [owner]);

    const {
        register,
        formState: { errors },
        handleSubmit,
        setValue,
    } = useForm<IFormInput>();

    const onSubmit: SubmitHandler<IFormInput> = (data) => TryEdit(data);

    const TryEdit = async (data: IFormInput) => {

        if (id !== undefined) {
            var res = await ownerService.update(id, {
                id: id,
                name: JSON.parse(`{"en": "${data.name}"}`),
                email: data.email,
                phone: data.phone,
                advancedPay: data.advancedPay,
                appUserId: jwt.appUserId,
            });

            console.log(res);
            if (res.status >= 300 && res.errorMessage) {
                // let errorMessage = res.status + " " + res.errorMessage;
            } else {
                navigate("/Owners");
            }

            console.log(jwt);
        }
    };

    return (
        <>
            <h1>Edit</h1>

            <h4>Owner</h4>
            <hr />

            <div className="row">
                <form className="col-md-4" onSubmit={handleSubmit(onSubmit)}>
                <div>
                        <div className="form-group">
                            <label className="control-label">Name</label>
                            <input
                                {...register("name", {
                                    required: true,
                                })}
                                className="form-control"
                                type="text"
                            />
                             <div className="text-danger form-text">
                                            {errors.name?.type ===
                                                "required" &&
                                                "Name is required"}
                                        </div>
                        </div>

                        <div className="form-group">
                        <label className="control-label">Email</label>
                                <input
                                    {...register("email", {
                                        required: true,
                                        minLength: 5,
                                    })}
                                    className="form-control"
                                    type="text"
                                />
                                <div className="text-danger form-text">
                                    {errors.email?.type === "required" &&
                                        "Email is required"}
                                    {errors.email?.type === "minLength" &&
                                        "Minimum email length is 5"}
                                </div>
                        </div>
                        <div className="form-group">
                            <label className="control-label">Phone</label>
                            <input
                            {...register("phone", {
                                required: true,
                            })}
                                className="form-control valid"
                                type="number"
                            />
                            <div className="text-danger form-text">
                                            {errors.phone?.type ===
                                                "required" &&
                                                "Phone is required"}
                                        </div>
                        </div>
                        <div className="form-group">
                            <label className="control-label">Advanced Pay</label>
                            <input
                                {...register("advancedPay", {
                                    required: false,
                                })}
                                className="form-control"
                                type="text"
                            />
                            
                        </div>
                       
                        <div className="form-group pt-2">
                        <input
                                    type="submit"
                                    value="Save"
                                    className="btn btn-primary"
                                />
                                <Link
                                to={`/Owners`}
                                className="btn btn-primary m-1"
                            >
                                Back to List{" "}
                            </Link>{" "}
                        </div>
                    </div>
                </form>
            </div>
        </>
    );
}

export default OwnerEdit;
