// ASP.NET + Javascript project/Javascript/vue-apartment-app/src/views/identity/Login.vue
<template>
  <h1>Login</h1>

  <hr />
  <div class="row">
    <div class="col-md-4">
      <div v-if="errorMessage != null" class="text-danger validation-summary-errors" data-valmsg-summary="true">
        <ul>
          <li>{{ errorMessage }}</li>
        </ul>
      </div>
      <div>
        <div class="form-group">
          <label class="control-label" for="FirstName">Email</label>
          <input v-model="email" class="form-control" type="text" />
        </div>
        <div class="form-group">
          <label class="control-label" for="LastName">Password</label>
          <input v-model="password" class="form-control" type="password" />
        </div>
        <div class="form-group">
          <input @click="loginClicked()" type="submit" value="Login" class="btn btn-primary" />
        </div>
      </div>
    </div>
  </div>

  <div>
    <a href="/Persons">Back to List</a>
  </div>
</template>

<script lang="ts">
import { useIdentityStore } from "@/stores/Identity";
import { Options, Vue } from "vue-class-component";
import { IdentityService } from "@/service/IdentityService";
import jwt_decode from "jwt-decode";
@Options({
  components: {},
  props: {},
  emist: {},
})
export default class Login extends Vue {
  identityStore = useIdentityStore();
  email: string = "";
  password: string = "";
  errorMessage: string | null = null;

  IdentityService = new IdentityService();

  async loginClicked(): Promise<void> {
    console.log("submitclicked");
    var res = await this.IdentityService.login(this.email, this.password);
    console.log(res);
    if (res.status === 200) {
      await this.$router.push("/");

      this.identityStore.$state.jwt = res.data!;
      let jwt = jwt_decode(this.identityStore.$state.jwt.token);
      this.identityStore.$state.jwt.appUserId = jwt["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"];
      console.log(this.identityStore.$state.jwt);
    } else {
    
    this.errorMessage = (res.status + " " + res.errorMessage)
    }

  }
}
</script>

// ASP.NET + Javascript project/Javascript/react-apartment-app/src/views/identity/Login.tsx
import { useForm, SubmitHandler } from "react-hook-form";
import { useNavigate } from "react-router-dom";
import { IdentityService } from "../../services/IdentityService";
import { useAppSelector, useAppDispatch } from "../../store/hooks";
import { update } from "../../store/identity";

interface IFormInput {
    email: string;
    firstName: string;
    lastName: string;
    password: string;
    confirmPassword: string;
}

function Login(): JSX.Element {
    const {
        register,
        formState: { errors },
        handleSubmit,
    } = useForm<IFormInput>();

    const onSubmit: SubmitHandler<IFormInput> = (data) => TryLogin(data);
    const jwt = useAppSelector((state) => state.identity);
    const dispatch = useAppDispatch();
    const navigate = useNavigate();

    const TryLogin = async (data: IFormInput) => {
        let identityService = new IdentityService();

        var res = await identityService.login(data.email, data.password);
        console.log(res);
        if (res.status === 200) {
            console.log("login Succesful");
            dispatch(update(res.data!));
            navigate("/");
        } else {
            console.log("login Unsuccesful");
            let errorMessage = res.status + " " + res.errorMessage;
        }

        console.log(jwt);
    };

    return (
        <>
            <h1>Login</h1>

            <hr />
            <div className="row">
                <form className="col-md-4" onSubmit={handleSubmit(onSubmit)}>
                    <div>
                        <div className="form-group">
                            <label className="control-label">Email</label>
                            <input
                                {...register("email", {
                                    required: true,
                                    minLength: 5,
                                })}
                                v-model="email"
                                className="form-control"
                                type="text"
                            />
                            <div className="text-danger form-text">
                                {errors.email?.type === "required" &&
                                    "Email is required"}
                                {errors.email?.type === "minLength" &&
                                    "Minimum email length is 5"}
                            </div>
                        </div>
                        <div className="form-group">
                            <label className="control-label">Password</label>
                            <input
                                {...register("password", { required: true })}
                                v-model="password"
                                className="form-control"
                                type="password"
                            />
                            <div className="text-danger form-text">
                                {errors.password?.type === "required" &&
                                    "Password is required"}
                            </div>
                        </div>
                        <div className="form-group">
                            <input
                                type="submit"
                                value="Login"
                                className="btn btn-primary"
                            />
                        </div>
                    </div>
                </form>
            </div>

            <div>
                <a href="/Persons">Back to List</a>
            </div>
        </>
    );
}

export default Login;
