// ASP.NET + Javascript project/Javascript/react-apartment-app/src/views/fund/FundDelete.tsx
import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { IAssociation } from "../../domain/IAssociation";
import { IFund } from "../../domain/IFund";
import { AssociationService } from "../../services/AssociationService";
import { FundService } from "../../services/FundService";

const initialFundState: IFund = {
    id: "",
    name: { en: "" },
    value: 0,
    associationId: "",
};

const initialAssociationState: IAssociation = {
    id: "",
    name: { en: "" },
    description: { en: "" },
    email: "",
    phone: 0,
    bankName: { en: "" },
    bankNumber: "",
    appUserId: "",
};

function FundDelete() {
    let { id } = useParams();
    const fundService = new FundService();
    const associationService = new AssociationService();
    const navigate = useNavigate();


    const [association, setAssociation] = useState(initialAssociationState);
    const [fund, setFund] = useState(initialFundState);

    useEffect(() => {
        console.log("did fund get")
        if (id !== undefined) {
            fundService.get(id).then((data) => setFund(data));
        }
    }, []);

    useEffect(() => {
        console.log("did association get")
        associationService.get(fund.associationId).then((data) => setAssociation(data));
        
    }, [fund]);

    const TryDelete = async () => {
        let errorMessages = [];

        if (id !== undefined) {
            var res = await fundService.delete(id);

            if (res.status >= 300 && res.errorMessage) {
                errorMessages.push(res.status + " " + res.errorMessage);
            } else {
                navigate("/Funds");
            }
        }

        errorMessages.push("Id not found");
    };
    
    return (
        <>
            <h1>Delete</h1>

            <div>
                <h4>Are you sure you want to delete this fund?</h4>
                <hr />
                <dl className="row">
                    
                    <dt className="col-sm-2">Name</dt>
                    <dd className="col-sm-10">{fund.name.en}</dd>
                    <dt className="col-sm-2">Value</dt>
                    <dd className="col-sm-10">{fund.value}</dd>
                    
                    <dt className="col-sm-2">Association</dt>
                    {(association.name !== undefined) &&
                    <dd className="col-sm-10">{association.name.en}</dd>}
                </dl>
            </div>
            <div>
                <button className="btn btn-danger" onClick={TryDelete}>Delete </button>{" "}
                <Link to={`/Funds`} className="btn btn-primary">
                    Back to List{" "}
                </Link>{" "}
            </div>
        </>
    );
}

export default FundDelete;

// ASP.NET + Javascript project/Javascript/vue-apartment-app/src/views/fund/FundDelete.vue
<template>
  <h1>Delete</h1>

  <h3>Are you sure you want to delete this?</h3>

  <div>
    <h4>Fund</h4>
    <hr />
    <dl class="row">
      <dt class="col-sm-2">Name</dt>
      <dd class="col-sm-10">{{ name }}</dd>
      <dt class="col-sm-2">Value</dt>
      <dd class="col-sm-10">{{ value }}</dd>
      <dt class="col-sm-2">Association</dt>
      <dd class="col-sm-10">{{ associationId }}</dd>
      
    </dl>
  </div>
  <div>
    <div>
      <div class="col-md-3 form-group btn-group">
        <input @click="deleteClicked()" type="submit" value="Delete" class="btn btn-danger p-2" />

        <RouterLink to="/fund" class="nav-link" active-class="active"> Back to List</RouterLink>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { FundService } from "@/service/FundService";
import { useFundStore } from "@/stores/fund";
import { useIdentityStore } from "@/stores/Identity";
import { Options, Vue } from "vue-class-component";

@Options({
  components: {},
  props: { id: String },
  emist: {},
})
export default class FundDelete extends Vue {
  id!: string;
  identityStore = useIdentityStore();
  fundStore = useFundStore();
  fundService = new FundService();

  associations: string[] = [];

  name: string = "";
  value: number | null = null;
  associationId: string | null = null;


  async deleteClicked(): Promise<void> {
    console.log("Delete clicked");

    var res = await this.fundService.delete(this.id);

    if (res.status >= 300 && res.errorMessage) {
      this.errorMessages.push(res.status + " " + res.errorMessage);
    } else {
      this.fundStore.$state.funds = await this.fundService.getAll();

      await this.$router.push("/fund");
    }
  }

  async mounted() {
    console.log("mounted");
    let fund = await this.fundService.get(this.id);
    console.log(this.fundStore.$state.funds);
    if (fund != null) {
      this.name = fund["name"]["en"];
      this.value = fund["value"];
      this.associationId = fund["associationId"];
    }
  }
}
</script>
