// ASP.NET + Javascript project/Javascript/react-apartment-app/src/views/associations/AssociationEdit.tsx
import { useEffect, useState } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import { Link, useNavigate, useParams } from "react-router-dom";
import { IAssociation } from "../../domain/IAssociation";
import { AssociationService } from "../../services/AssociationService";
import { useAppSelector } from "../../store/hooks";

const initialState: IAssociation = {
    id: "",
    name: { en: "" },
    description: { en: "" },
    email: "",
    phone: 0,
    bankName: { en: "" },
    bankNumber: "",
    appUserId: "",
};

interface IFormInput {
    name: string;
    description: string;
    email: string;
    phone: number;
    bankName: string;
    bankNumber: string;
}

function AssociationEdit() {
    let { id } = useParams();
    const associationService = new AssociationService();
    const jwt = useAppSelector((state) => state.identity);
    const navigate = useNavigate();

    const [association, setAssociation] = useState(initialState);

    useEffect(() => {
        console.log("did edit");
        if (id !== undefined) {
            associationService.get(id).then((data) => setAssociation(data));

            console.log(association);
        }
        console.log(association);
    }, []);

    useEffect(() => {
        setValue("name", association.name.en);
        if (association.description !== undefined) {
            setValue("description", association.description?.en);
        }
        setValue("email", association.email);
        setValue("phone", association.phone);
        if (association.bankName !== undefined) {
            setValue("bankName", association.bankName?.en);
        }
        if (association.bankNumber !== undefined) {
            setValue("bankNumber", association.bankNumber);
        }
    }, [association]);

    const {
        register,
        formState: { errors },
        handleSubmit,
        setValue,
    } = useForm<IFormInput>();

    const onSubmit: SubmitHandler<IFormInput> = (data) => TryEdit(data);

    const TryEdit = async (data: IFormInput) => {
        const associationService = new AssociationService();

        if (id !== undefined) {
            var res = await associationService.update(id, {
                id: id,
                name: JSON.parse(`{"en": "${data.name}"}`),
                description: JSON.parse(`{"en": "${data.description}"}`),
                email: data.email,
                phone: data.phone,
                bankName: JSON.parse(`{"en": "${data.bankName}"}`),
                bankNumber: data.bankNumber,
                appUserId: jwt.appUserId,
            });

            console.log(res);
            if (res.status >= 300 && res.errorMessage) {
                // let errorMessage = res.status + " " + res.errorMessage;
            } else {
                navigate("/Associations");
            }

            console.log(jwt);
        }
    };

    return (
        <>
            <h1>Create</h1>

            <h4>Associations</h4>
            <hr />

            <div className="row">
                <form className="col-md-4" onSubmit={handleSubmit(onSubmit)}>
                    <div>
                        <div className="form-group">
                            <label className="control-label">Name</label>
                            <input
                                {...register("name", {
                                    required: true,
                                })}
                                className="form-control"
                                type="text"
                            />
                            <div className="text-danger form-text">
                                {errors.name?.type === "required" &&
                                    "Name is required"}
                            </div>
                        </div>
                        <div className="form-group">
                            <label className="control-label">Description</label>
                            <input
                                {...register("description", {
                                    required: false,
                                })}
                                className="form-control"
                                type="text"
                            />
                        </div>

                        <div className="form-group">
                            <label className="control-label">Email</label>
                            <input
                                {...register("email", {
                                    required: true,
                                })}
                                className="form-control"
                                type="text"
                            />
                            <div className="text-danger form-text">
                                {errors.email?.type === "required" &&
                                    "Email is required"}
                            </div>
                        </div>
                        <div className="form-group">
                            <label className="control-label">Phone</label>
                            <input
                                {...register("phone", {
                                    required: true,
                                })}
                                className="form-control valid"
                                type="number"
                            />
                            <div className="text-danger form-text">
                                {errors.phone?.type === "required" &&
                                    "Phone is required"}
                            </div>
                        </div>
                        <div className="form-group">
                            <label className="control-label">Bank name</label>
                            <input
                                {...register("bankName", {
                                    required: false,
                                })}
                                className="form-control"
                                type="text"
                            />
                        </div>
                        <div className="form-group">
                            <label className="control-label">Bank number</label>
                            <input
                                {...register("bankNumber", {
                                    required: false,
                                })}
                                className="form-control"
                                type="text"
                            />
                        </div>

                        <div className="form-group pt-1">
                            <input
                                type="submit"
                                value="Save"
                                className="btn btn-primary m-1"
                            />
                            <Link
                                to={`/Associations/`}
                                className="btn btn-primary m-1"
                            >
                                Back to List{" "}
                            </Link>{" "}
                           
                        </div>
                    </div>
                </form>
            </div>
        </>
    );
}

export default AssociationEdit;

// ASP.NET + Javascript project/Javascript/vue-apartment-app/src/views/association/AssociationEdit.vue
<template>
  <h1>Edit</h1>

  <h4>Association</h4>
  <hr />
  <div>
    <ul>
      <li class="text-danger" v-for="error in errorMessages" :key="error">
        {{ error }}
      </li>
    </ul>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div>
        <div class="form-group">
          <label class="control-label" for="Association_Name">Name</label>
          <input v-model="name" class="form-control" type="text" />
        </div>
        <div class="form-group">
          <label class="control-label" for="Association_Description">Description</label>
          <input v-model="description" class="form-control" type="text" />
        </div>
        <div class="form-group">
          <label class="control-label" for="Association_Email">Email</label>
          <input v-model="email" class="form-control" type="text" />
        </div>
        <div class="form-group">
          <label class="control-label" for="Association_Phone">Phone</label>
          <input v-model="phone" class="form-control valid" type="number" />
        </div>
        <div class="form-group">
          <label class="control-label" for="Association_BankName">Bank name</label>
          <input v-model="bankname" class="form-control" type="text" />
        </div>
        <div class="form-group">
          <label class="control-label" for="Association_BankNumber">Bank number</label>
          <input v-model="banknumber" class="form-control" type="text" />
        </div>

        <div class="form-group btn-group pt-3">
          <input @click="submitClicked()" type="submit" value="Edit" class="btn btn-primary" />
          <RouterLink to="/association" class="nav-link" active-class="active"> Back to List</RouterLink>
        </div>
        <div>
    
  </div>
      </div>
    </div>
  </div>

  
</template>

<script lang="ts">
import { useAssociationsStore } from "@/stores/association";
import { AssociationService } from "@/service/AssociationService";
import { Options, Vue } from "vue-class-component";
import { useIdentityStore } from "@/stores/Identity";

@Options({
  components: {},
  props: { id: String },
  emist: {},
})
export default class AssociationEdit extends Vue {
  id!: string;
  identityStore = useIdentityStore();
  associationStore = useAssociationsStore();
  associationService = new AssociationService();
  errorMessages: string[] = [];

  appUserId: string = "";
  name: string = "";
  description?: string = "";
  email: string = "";
  phone: number | null = null;
  bankname?: string = "";
  banknumber?: string = "";

  async submitClicked(): Promise<void> {
    console.log("submitclicked");

    this.errorMessages = [];

    if (this.name === "") {
      this.errorMessages.push("Name cannot be empty");
    }

    if (this.phone === null) {
      this.errorMessages.push("Phone number cannot be empty");
    }

    if (this.email.length < 6) {
      this.errorMessages.push("Email must be longer than 5");
    }

    if (this.errorMessages.length === 0) {
      let appUserId = this.identityStore.$state.jwt!.appUserId;

      if (appUserId === null) {
        await this.$router.push("/");
        return;
      }

      var res = await this.associationService.update(this.id, {
        id: this.id,
        name: { "en": this.name },
        description: { "en": this.description },
        email: this.email,
        phone: this.phone,
        bankName: { "en": this.bankname },
        bankNumber: this.banknumber,
        appUserId: appUserId,
      });

      if (res.status >= 300 && res.errorMessage) {
        this.errorMessages.push(res.status + " " + res.errorMessage);
      } else {
        this.associationStore.$state.associations = await this.associationService.getAll();

        await this.$router.push("/association");
      }
    }
  }

  async mounted() {
    console.log("mounted");
    let association = await this.associationService.get(this.id);
    console.log(this.associationStore.$state.associations);
    if (association != null) {
      this.name = association["name"]["en"];
      this.description = association["description"]? association["description"]["en"] : undefined;
      this.email = association["email"];
      this.phone = association["phone"];
      this.bankname = association["bankName"]? association["bankName"]["en"] : undefined;
      this.banknumber = association["bankNumber"];
    }
  }
}
</script>
