// ASP.NET + Javascript project/Javascript/vue-apartment-app/src/views/fund/FundDetails.vue
<template>
  <h1>Details</h1>

  <div>
    <h4>Fund</h4>
    <hr />
    <dl class="row">
      <dt class="col-sm-2">Name</dt>
      <dd class="col-sm-10">{{ name }}</dd>
      <dt class="col-sm-2">Value</dt>
      <dd class="col-sm-10">{{ value }}</dd>
      <dt class="col-sm-2">Association</dt>
      <dd class="col-sm-10">{{ associationId }}</dd>
      
    </dl>
  </div>
  <div>
    <div class="btn-group ">
      
        <RouterLink :to="{ name: 'fundedit', params: { id: id } }" type="submit">Edit</RouterLink> |
      
        <RouterLink to="/fund" type="submit"> Back to List</RouterLink>
      
    </div>
  </div>
</template>

<script lang="ts">
import { FundService } from "@/service/FundService";
import { useFundStore } from "@/stores/fund";
import { useIdentityStore } from "@/stores/Identity";
import { Options, Vue } from "vue-class-component";

@Options({
  components: {},
  props: { id: String },
  emist: {},
})
export default class FundDetials extends Vue {
  id!: string;
  identityStore = useIdentityStore();
  fundStore = useFundStore();
  fundService = new FundService();

  associations: string[] = [];

  name: string = "";
  value: number | null = null;
  associationId: string | null = null;

 async mounted() {
    console.log("mounted");
    let fund = await this.fundService.get(this.id);
    console.log(this.fundStore.$state.funds);
    if (fund != null) {
      this.name = fund["name"]["en"];
      this.value = fund["value"];
      this.associationId = fund["associationId"];
    }
  }
}
</script>

// ASP.NET + Javascript project/Javascript/react-apartment-app/src/views/fund/FundDetails.tsx
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { IAssociation } from "../../domain/IAssociation";
import { IFund } from "../../domain/IFund";
import { AssociationService } from "../../services/AssociationService";
import { FundService } from "../../services/FundService";

const initialFundState: IFund = {
    id: "",
    name: { en: "" },
    value: 0,
    associationId: "",
};

const initialAssociationState: IAssociation = {
    id: "",
    name: { en: "" },
    description: { en: "" },
    email: "",
    phone: 0,
    bankName: { en: "" },
    bankNumber: "",
    appUserId: "",
};

function FundDetails() {
    let { id } = useParams();
    const fundService = new FundService();
    const associationService = new AssociationService();

    const [association, setAssociation] = useState(initialAssociationState);
    const [fund, setFund] = useState(initialFundState);

    useEffect(() => {
        if (id !== undefined) {
            fundService.get(id).then((data) => setFund(data));
        }
    }, []);

    useEffect(() => {
        associationService
            .get(fund.associationId)
            .then((data) => setAssociation(data));
    }, [fund]);

    return (
        <>
            <h1>Details</h1>

            <div>
                <h4>Fund</h4>
                <hr />
                <dl className="row">
                    <dt className="col-sm-2">Name</dt>
                    <dd className="col-sm-10">{fund.name.en}</dd>
                    <dt className="col-sm-2">Value</dt>
                    <dd className="col-sm-10">{fund.value}</dd>

                    <dt className="col-sm-2">Association</dt>
                    {association.name !== undefined && (
                        <dd className="col-sm-10">{association.name.en}</dd>
                    )}
                </dl>
            </div>

            <div>
                <Link
                    to={`/Funds/Edit/${id}`}
                    className="btn btn-primary"
                >
                    Edit{" "}
                </Link>{" "}
                <Link to={`/Funds/`} className="btn btn-primary">
                    Back to List{" "}
                </Link>{" "}
            </div>
        </>
    );
}

export default FundDetails;
