// ASP.NET + Javascript project/Javascript/vue-apartment-app/src/views/fund/FundCreate.vue
<template>
  <h1>Create</h1>

  <h4>Fund</h4>
  <hr />
  <div>
    <ul>
      <li class="text-danger" v-for="error in errorMessages" :key="error">
        {{ error }}
      </li>
    </ul>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div>
        <div class="form-group">
          <label class="control-label">Name</label>
          <input v-model="name" class="form-control" type="text" />
        </div>
        <div class="form-group">
          <label class="control-label">Value</label>
          <input v-model="value" class="form-control valid" type="number" />
        </div>
        <div class="form-group">
          <label class="control-label" for="Fund_AssociationId">Association ID</label>
          <select v-model="associationId" class="form-control valid" >
            <option v-bind:value="association.id" v-for="association in associationStore.associations" :key="association.id">{{ association.name }}</option>
          </select>
        </div>
        <div class="form-group pt-2">
          <input @click="submitClicked()" type="submit" value="Create" class="btn btn-primary" />
        </div>
      </div>
    </div>
  </div>

  <div>
    <RouterLink to="/fund" class="nav-link" active-class="active"> Back to List</RouterLink>
  </div>
</template>

<script lang="ts">
import { useFundStore } from "@/stores/fund";
import { FundService } from "@/service/FundService";
import { Options, Vue } from "vue-class-component";
import { useIdentityStore } from "@/stores/Identity";
import { AssociationService } from "@/service/AssociationService";
import { useAssociationsStore } from "@/stores/association";

@Options({
  components: {},
  props: {},
  emist: {},
})
export default class FundCreate extends Vue {
  identityStore = useIdentityStore();
  fundStore = useFundStore();
  fundService = new FundService();

  associationService = new AssociationService();
  associationStore = useAssociationsStore();
  associations: string[] = [];
  errorMessages: string[] = [];

  name: string = "";
  value: number | null = null;
  associationId: string | null = null;

  async submitClicked(): Promise<void> {
    console.log("Register clicked");
    this.errorMessages = [];

    if (this.name === "") {
      this.errorMessages.push("Name cannot be empty");
    }

    if (this.value === null) {
      this.errorMessages.push("Value cannot be empty");
    }

    if (this.value === null) {
      this.errorMessages.push("Must select one association");
    }

    if (this.errorMessages.length === 0) {

      var res = await this.fundService.add({
        name: { en: this.name },
        value: this.value,
        associationId: this.associationId
      });

      if (res.status >= 300 && res.errorMessage) {
        this.errorMessages.push(res.status + " " + res.errorMessage);
      } else {
        this.fundStore.$state.funds = await this.fundService.getAll();

        await this.$router.push("/fund");
      }
    }
  }

  async mounted(): Promise<void> {
    this.associationStore.$state.associations = await this.associationService.getAll();
  }
}
</script>

// ASP.NET + Javascript project/Javascript/react-apartment-app/src/views/fund/FundCreate.tsx
import { useEffect, useState } from "react";
import { SubmitHandler, useForm } from "react-hook-form";
import { Link, useNavigate } from "react-router-dom";
import { IAssociation } from "../../domain/IAssociation";

import { AssociationService } from "../../services/AssociationService";
import { FundService } from "../../services/FundService";

const initialState: IAssociation[] = [];

interface IFormInput {
    name: string;
    value: number;
    associationId: string;
}

function FundCreate() {
    const associationService = new AssociationService();

    const navigate = useNavigate();
    const [associations, setAssociations] = useState(initialState);

    useEffect(() => {
        associationService.getAll().then((data) => setAssociations(data));
    }, []);

    const {
        register,
        formState: { errors },
        handleSubmit,
    } = useForm<IFormInput>();

    const onSubmit: SubmitHandler<IFormInput> = (data) => TryCreate(data);

    const TryCreate = async (data: IFormInput) => {
        const fundService = new FundService();

        console.log("submit pressed")
        
        console.log(data.associationId)
            var res = await fundService.add({
                name: JSON.parse(`{"en": "${data.name}"}`),
                value: data.value,
                associationId: data.associationId
            });

            console.log(res);
            if (res.status >= 300 && res.errorMessage) {
                // let errorMessage = res.status + " " + res.errorMessage;
            } else {
                navigate("/Funds");
            }

        // let errorMessage = "Association id not found";
    };

    return (
        <>
            <h1>Create</h1>

            <h4>Fund</h4>
            <hr />

            <div className="row">
                <form className="col-md-4" onSubmit={handleSubmit(onSubmit)}>
                    <div>
                        <div className="form-group">
                            <label className="control-label">Name</label>
                            <input
                                {...register("name", {
                                    required: true,
                                })}
                                className="form-control"
                                type="text"
                            />
                            <div className="text-danger form-text">
                                {errors.name?.type === "required" &&
                                    "Name is required"}
                            </div>
                        </div>
                        <div className="form-group">
                            <label className="control-label">Value</label>
                            <input
                                {...register("value", {
                                    required: false,
                                })}
                                className="form-control"
                                type="number"
                            />
                        </div>

                        <div className="form-group">
                            <label className="control-label">Association Name</label>
                            <select
                                {...register("associationId", {
                                    required: true,
                                })}
                                className="form-control"
                            >   
                                <option  selected disabled hidden>***</option>
                                {associations.map((item) => {
                                    return <option key={item.id} value={item.id}>{item.name.en}</option>;
                                })}
                            </select>
                            <div className="text-danger form-text">
                                {errors.associationId?.type === "required" &&
                                    "Association is required"}
                            </div>
                        </div>
                        <div className="form-group pt-1">
                            <input
                                type="submit"
                                value="Create"
                                className="btn btn-primary"
                            />
                            <Link
                                to={`/Funds`}
                                className="btn btn-primary m-1"
                            >
                                Back to List{" "}
                            </Link>{" "}
                        </div>
                    </div>
                </form>
            </div>

            <div></div>
        </>
    );
}

export default FundCreate;
